version: '3'
services:
  ui:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - query
    volumes:
      - ./client:/usr/src
      - '/app/node_modules'

  comments:
    build: ./comments
    ports:
      - '4001:4001'
    volumes:
      - ./comments:/usr/src
    environment:
      - EVENT_BUS_URI=http://event-bus:4005

  moderation:
    build: ./moderation
    ports:
      - '4003:4003'
    volumes:
      - ./moderation:/usr/src
    environment:
      - EVENT_BUS_URI=http://event-bus:4005

  posts:
    build: ./posts
    ports:
      - '4000:4000'
    volumes:
      - ./posts:/usr/src
    environment:
      - EVENT_BUS_URI=http://event-bus:4005

  event-bus:
    build: ./event-bus
    ports:
      - '4005:4005'
    depends_on:
      - comments
      - moderation
      - posts
    volumes:
      - ./event-bus:/usr/src
    environment:
      - COMMENTS_URI=http://comments:4001
      - MODERATION_URI=http://moderation:4003
      - QUERY_URI=http://query:4002
      - POSTS_URI=http://posts:4000

  query:
    build: ./query
    ports:
      - '4002:4002'
    depends_on:
      - event-bus
    volumes:
      - ./query:/usr/src
    environment:
      - EVENT_BUS_URI=http://event-bus:4005