version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - auth
      - client
      - mongodb

  auth:
    container_name: auth-service
    build: ./auth
    expose:
      - 4000
    depends_on:
      - mongodb
    env_file:
    - ./auth/prod.env

  client:
    container_name: client
    build: ./client
    expose:
      - 3000
    environment:
      - API_AUTH=auth

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017