version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - auth
      - client
    links:
      - auth
      - client

  auth:
    container_name: auth-service
    build: ./auth
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    env_file:
    - ./auth/prod.env

  client:
    container_name: client
    build: ./client
    ports:
      - '3000:3000'

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongodb
    ports:
      - '8081:8081'