version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - auth
      - client
      - mongodb
    networks:
      - app-network

  auth:
    container_name: auth-service
    build: ./auth
    expose:
      - 4000
    depends_on:
      - mongodb
    env_file:
    - ./auth/prod.env
    networks:
      - app-network

  client:
    container_name: client
    build: ./client
    expose:
      - 3000
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb
    expose:
      - 27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge