version: '3'
services:
  auth:
    build: ./auth
    ports:
      - '4000:4000'
    depends_on:
      - mongodb
    env_file:
    - ./auth/prod.env

  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./usr/src/client:/base
      - ./usr/src/client/node_modules:/base/node_modules

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - mongodb
    ports:
      - '8081:8081'